#!/usr/bin/env bash

# Colors
bg='1e1e2e' bgl='313244' fg='d9e0ee'
red='eb6f92' green='ebbcba' yellow='f6c177'
blue='31748f' magenta='#c4a7e7' cyan='#f6c177'
alpha='00000000'

# CMD
swaylock -f \
	`# General` \
  --screenshots \
  --clock \
  --indicator \
	--indicator-radius 100 \
	--indicator-thickness 7 \
  --effect-blur 7x5 \
	--effect-vignette 0.5:0.5 \
    --ignore-empty-password \
	--show-failed-attempts \
	--hide-keyboard-layout \
	--indicator-caps-lock \
	`# Appearance - change CC to your desired transparency` \
	--color ${bg}FF \
	`#--image ${IMAGE} --scaling fill` \
	--font 'Noto Sans' --font-size 30 \
	`# Backspace Key` \
	--key-hl-color ${green} \
	--caps-lock-key-hl-color ${blue} \
	--bs-hl-color ${red} \
	--caps-lock-bs-hl-color ${red} \
	`# Indicator` \
	--indicator-radius 120 \
	--indicator-thickness 10 \
	`# Inside Circle Colors` \
	--inside-color ${alpha} \
	--inside-clear-color ${alpha} \
	--inside-caps-lock-color ${alpha} \
	--inside-ver-color ${blue} \
	--inside-wrong-color ${red} \
	`# Layout Colors` \
	--layout-bg-color ${cyan} \
	--layout-border-color ${cyan} \
	--layout-text-color ${bg} \
	`# Line Colors` \
	--line-color ${bg} \
	--line-clear-color ${red} \
	--line-caps-lock-color ${bg} \
	--line-ver-color ${bg} \
	--line-wrong-color ${bg} \
	`# Ring Colors` \
	--ring-color ${cyan} \
	--ring-clear-color ${bg} \
	--ring-caps-lock-color ${magenta} \
	--ring-ver-color ${blue} \
	--ring-wrong-color ${red} \
	`# Separator Color` \
	--separator-color ${bg} \
	`# Text Colors` \
	--text-color ${fg} \
	--text-clear-color ${fg} \
	--text-caps-lock-color ${fg} \
	--text-ver-color ${bg} \
	--text-wrong-color ${bg} \
	--indicator-caps-lock
